package com.redhat.consulting.brms.workshop

//list any import classes here.
import com.redhat.consulting.brms.workshop.model.Event
import com.redhat.consulting.brms.workshop.model.EventPass
import com.redhat.consulting.brms.workshop.model.IsAdult
import com.redhat.consulting.brms.workshop.model.Person
import com.redhat.consulting.brms.workshop.model.Ticket
import com.redhat.consulting.brms.workshop.model.TicketOffer
import com.redhat.consulting.brms.workshop.model.TicketOffers
import com.redhat.consulting.brms.workshop.model.Venue

//declare any global variables here
global com.redhat.consulting.brms.workshop.model.TicketOffers ticketOffers;


/*
	Concepts: Tickets of type D cannot be sold to non-adults.
	Non-adults get a 25% discount on tickets.
	Persons with a special event pass get 10% discount on top of all discounts.
	Golden tickets can only be sold to people with an Event pass.
*/

rule "Create TicketOffers"
when 
	$t: Ticket() 
then 
	TicketOffer tOffer = new TicketOffer($t);
	ticketOffers.addTicket(tOffer);
	insert(tOffer);
end


rule "Filter Tickets Adults"
when
	$p:Person(age < 18)
	$t:Ticket(event.rating == Event.EVENT_RATING.D)
then
	retract($t)
end
